version: '3.3'
services:

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    restart: on-failure
    volumes:
      - ./logstash/prod:/logstash_dir
      - ./logstash/pipelines.yml:/logstash_dir/pipelines.yml
    command: logstash --path.settings=/logstash_dir
    tty: true
    ports:
      - 9600:9600
